services:
  - type: web
    name: predictcup-backend
    runtime: node
    region: oregon
    plan: free
<<<<<<< Updated upstream
    buildCommand: npm install && npx prisma generate
    startCommand: npm run start:prod
=======

    buildCommand: cd backend && npm install && npm run prisma:generate
    startCommand: cd backend && npm start

>>>>>>> Stashed changes
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: predictcup-db
          property: connectionString
      - key: BOT_TOKEN
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

databases:
  - name: predictcup-db
    region: oregon
    plan: free
